import "./tests/importJson.test.js";
import "./tests/find.test.js";
import "./tests/logicalOperators.test.js";
import "./tests/comparisonOperators.test.js";
import "./tests/elementQueryOperators.test.js";
import "./tests/evaluationOperators.test.js";
import "./tests/arrayQueryOperators.test.js";
import "./tests/projectionOperators.test.js";
import "./tests/miscellaneousQueryOperators.test.js";